import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { ORDER_API } from "../config";

// Define a service using a base URL and expected endpoints
export const orderAPI = createApi({
  reducerPath: "orderManagement",
  tagTypes: ["OrderList"],
  baseQuery: fetchBaseQuery({ baseUrl: ORDER_API }),
  endpoints: (builder) => ({
    getAllOrders: builder.query({
      query: () => `orders`,

      providesTags: (result, _error, _arg) =>
        result
          ? [
              ...result.map(({ id }) => ({ type: "orderManagement", id })),
              { type: "OrderList", id: "LIST" },
            ]
          : [{ type: "OrderList", id: "LIST" }],
    }),
  }),
});

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
// Hooks are auto-generated by RTK-Query
export const { useGetAllOrdersQuery } = orderAPI;
