import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { API_URL } from "../config/index";
import { selectToken } from "../slices/auth.slice";

export const promotionAPI = createApi({
  reducerPath: "PromotionManagement",
  tagTypes: ["PromotionList"],
  baseQuery: fetchBaseQuery({
    baseUrl: API_URL,
    prepareHeaders: (headers, { getState }) => {
      const token = selectToken(getState()); // Retrieve token from Redux state using selectToken selector
      if (token) {
        headers.append("Authorization", `Bearer ${token}`);
      }
      headers.append("Content-Type", "application/json");
      return headers;
    },
  }),
  endpoints: (builder) => ({
    getPromotions: builder.query({
      query: () => `promotions/getAll`,
      providesTags: (result, _error, _arg) =>
        result
          ? [
              ...result.map(({ id }) => ({ type: "PromotionManagement", id })),
              { type: "PromotionList", id: "LIST" },
            ]
          : [{ type: "PromotionList", id: "LIST" }],
    }),
    getPromotionById: builder.query({
      query: (id) => `promotions/${id}`,
      providesTags: (result, error, id) => [{ type: "PromotionList", id }],
    }),

    getPromotionByCode: builder.query({
      query: (code) => `promotions/getByCode/12?code=${code}`,
      providesTags: (result, error, id) => [{ type: "PromotionList", id }],
    }),

    addPromotions: builder.mutation({
      query: (body) => {
        return {
          method: "POST",
          url: `promotions/create`,
          body,
        };
      },
      invalidatesTags: [{ type: "PromotionList", id: "LIST" }],
    }),

    updateStatus: builder.mutation({
      query: ({ id, status }) => {
        return {
          method: "PUT",
          url: `/promotions/status/${id}`,
          body: {
            status: status,
          },
        };
      },
      invalidatesTags: [{ type: "PromotionList", id: "LIST" }],
    }),
    updatePromotion: builder.mutation({
      query: ({ id, body }) => {
        return {
          method: "PUT",
          url: `/promotions/status/${id}`,
          body: body,
        };
      },
      invalidatesTags: [{ type: "PromotionList", id: "LIST" }],
    }),
  }),
});

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
// Hooks are auto-generated by RTK-Query
export const {
  useGetPromotionsQuery,
  useGetPromotionByIdQuery,
  useAddPromotionsMutation,
  useUpdateStatusMutation,
  useUpdatePromotionMutation,
  useLazyGetPromotionByCodeQuery,
} = promotionAPI;
